Initialize field `owner` in `file_operations` (issue #214)
Rust-for-Linux/linux pull request #228
Opened 2021-04-25 16:47 UTC by kittenz

Fix for the issue #214

Struct `ThisModule` in lib.rs seems to be the equivalent of THIS_MODULE and according to [this StackOverflow](https://stackoverflow.com/questions/48478978/regarding-owner-field-of-struct-file-operations) the owner field should be initialized to THIS_MODULE.
Just point me to the right direction if this isn't the correct way to do it. I'm pretty new to contributing to the Linux kernel.

2021-04-26 19:37 UTC, ojeda requested changes
Thanks!

Please note that this is taking the tuple constructor function and using its address as the owner. The Rust equivalent would be `THIS_MODULE` (a per-module value), rather than `ThisModule` (a type).

2021-04-26 19:49 UTC, wedsonaf commented
> Please note that this is taking the tuple constructor function and using its address as the owner. The Rust equivalent would be `THIS_MODULE` (a per-module value), rather than `ThisModule` (a type).

+1

Also note that `crate::THIS_MODULE` is the kernel one, which is not what we want. I think you'll need to take a module as argument. The challenge is to do it safely.

2021-04-27 12:33 UTC, kittenz commented
Take module as an argument? It's a struct, not a function that can take arguments. What part of the code are you referring to?

2021-04-27 12:40 UTC, wedsonaf commented
> Take module as an argument? It's a struct, not a function that can take arguments. What part of the code are you referring to?

This struct is a private member of `FileOperationsVtable`. It is exposed externally via `FileOperationsVtable::build`.

2021-04-27 14:14 UTC, kittenz commented
I can't take `module: *mut bindings::module` as an argument for `FileOperationsVtable::build` because there is no way to set  `Self::VTABLE.owner` to that. I've been staring at Google search results for hours without an answer (which is probably something very simple).

2021-04-28 07:09 UTC, Kloenk commented
As far as I can see it, with the current implementation of FileOperationsVtable this is. It possible. Const and const dm is evaluated at build time. But the address of THIS_MODULE can not be known then. 

A working way could be a proc_macro like I build for the rtnl_link_ops in #208 which then creates a static (mut)

2021-04-28 08:49 UTC, adamrk commented
Could we change `build` to return an owned `FileOperationsVtable`, then mutate the `owner` field and pin it before passing to the C side?

2021-04-28 12:12 UTC, wedsonaf commented
I don't have a solution for this yet, that's why I opened this bug... But the following are desirable aspects of an eventual solution:

1. The vtable is `const`: this is desirable for security reasons, specifically to avoid exploits that go from arbitrary write to arbitrary execution by easily changing pointers in the vtable, then triggering a code path that uses the vtable. (I know there are other ways to do this, but I don't want rust vtables to be _another_ way of doing it.)
2. The above may not be possible today in Rust, if that's the case we should bring it up with the Rust folks to see if they can enable this for us eventually.
3. If we go the route of having a mutable vtable, this should only apply to vtables in modules. That is, if the code is built into the kernel, then THIS_MODULE is 0 and we should have a `const` vtable.
4. Ideally the interface should be safe: that is, we need to prevent users from passing the wrong THIS_MODULE to any function that requires this (e.g., where the code is in module A but THIS_MODULE belongs to module B).
5. If we can't achieve no 4 above, we need to make the function `unsafe` and annotate the requirement that it's the caller's responsibility to ensure the requirement.

(This is not a super easy task, apologies for not making it clear earlier.)

2021-04-28 12:16 UTC, ojeda commented
> Ideally the interface should be safe: that is, we need to prevent users from passing the wrong THIS_MODULE to any function that requires this (e.g., where the code is in module A but THIS_MODULE belongs to module B).

Related: https://github.com/Rust-for-Linux/linux/issues/212.

2021-04-28 14:25 UTC, kittenz commented
Just pushed some code to the branch. `build` now returns `bindings::file_operations` & vtable is mutable.

The code obviously isn't done yet.

The vtable isn't a constant and I had to remove the const keyword from the build function, as you cannot use those `Some(something_callback::<T>)` in constants. As @wedsonaf pointed out, it's a security risk to have a mutable vtable.

2021-04-28 14:28 UTC, wedsonaf commented
If the code isn't done yet, please mark it as a draft so that we only spend time reviewing it when it's done.

Also, isn't the file_operations returned by `build` immediately destroyed (leaving you with a dangling pointer in `fops`)? We need to be careful with our usage of `unsafe`.

2021-04-28 14:30 UTC, closed without merging

2021-04-28 14:32 UTC, kittenz commented
Oops - undone

(The PR was closed until I push stuff to the branch for some reason)