Add EADDRNOTAVAIL error to rust
Rust-for-Linux/linux pull request #455
Opened 2021-07-23 12:21 UTC by Kloenk

This will be used for network drivers. (#439)

2021-07-23 15:11 UTC, ojeda requested changes

2021-07-23 15:11 UTC, ojeda commented on rust/kernel/error.rs
> +    /// Cannot assign requested address
```suggestion
    /// Cannot assign requested address.
```

2021-07-23 15:13 UTC, ojeda commented
Perhaps we should add all the ones from `include/uapi/asm-generic/errno.h`.

2021-07-24 07:31 UTC, Kloenk commented on rust/kernel/error.rs
> +    /// Cannot assign requested address
Will fix after the recording

2021-07-24 07:32 UTC, Kloenk commented
> Perhaps we should add all the ones from `include/uapi/asm-generic/errno.h`.

That would probably be a good idea. But doing it from hand is not the best work to do :-).

Maybe we can build some Marco to do it?

2021-08-20 10:15 UTC, Kloenk commented
What about a short macro to make it easier, eg that you have to write it like this to declare `ENOEXEC`:
~~~rs
/// Exec format error.
declare_err!(ENOEXEC);

2021-08-20 10:16 UTC, bjorn3 commented
I think the doc comment will need to be inside the macro invocation for this to work.

2021-08-20 10:17 UTC, Kloenk commented
really? if the macro just expands to `pub const ENOEXEC: Self = Error(-(bindings::ENOEXEC as i32));`?

2021-08-20 10:17 UTC, Kloenk commented
I think I will just try it out

2021-08-20 10:26 UTC, Kloenk commented
Yes, sadly you are right, I think it's still a bit easier to write `declare_err!("Operation not permitted.", EPERM);` instead of `pub const EPERM: Self = Error(-(bindings::EPERM as i32));`

2021-08-20 11:14 UTC, kloenk commented
rebased and moved to the macro, Will add missing errors now

2021-08-20 11:59 UTC, Kloenk commented
@ojeda I now included all errors from `include/uapi/asm-generic/errno.h` as requested.

2021-08-23 12:49 UTC, merged